# Generated by Django 6.0 on 2026-04-20 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'Whatsapp'), ('SMS', 'Sms'), ('EMAIL', 'Email'), ('KIOSK', 'Kiosk')], max_length=20)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('template_body', models.JSONField(blank=True, null=True)),
                ('reference_type', models.CharField(choices=[('ENCOUNTER', 'Encounter'), ('SERVICE_REQUEST', 'Service Request')], max_length=50)),
                ('event_type', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('RESULT_READY', 'Result Ready')], max_length=50)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DELAYED', 'Delayed')], default='IMMEDIATE', max_length=20)),
                ('delay_in_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
