# Generated by Django 6.0 on 2026-04-21 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_communication', '0001_initial'),
        ('emr', '0077_tagconfig_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('reference_id', models.UUIDField()),
                ('reference_type', models.CharField(choices=[('ENCOUNTER', 'Encounter'), ('SERVICE_REQUEST', 'Service Request')], max_length=50)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'Whatsapp'), ('SMS', 'Sms'), ('EMAIL', 'Email'), ('KIOSK', 'Kiosk')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('flow_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('context', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('reference_id', models.UUIDField()),
                ('reference_type', models.CharField(choices=[('ENCOUNTER', 'Encounter'), ('SERVICE_REQUEST', 'Service Request')], max_length=50)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_category', models.CharField(choices=[('CLEANLINESS', 'Cleanliness'), ('STAFF_BEHAVIOR', 'Staff Behavior'), ('WAIT_TIME', 'Wait Time'), ('TREATMENT_SATISFACTION', 'Treatment Satisfaction'), ('OTHER', 'Other')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care_communication.communicationsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='communicationsession',
            index=models.Index(fields=['patient', 'channel', 'status'], name='care_commun_patient_088f02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientfeedback',
            unique_together={('patient', 'reference_type', 'reference_id', 'issue_category')},
        ),
    ]
