# Generated by Django 6.0 on 2026-04-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_communication', '0002_communicationsession_patientfeedback_and_more'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='facility',
            field=models.ForeignKey(default='1234', on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
            preserve_default=False,
        ),
    ]
